# Generated by Django 3.1.5 on 2021-01-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinary',
            name='county',
            field=models.CharField(default='Nairobi', max_length=30),
        ),
        migrations.AlterField(
            model_name='veterinary',
            name='email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='veterinary',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
