# Generated by Django 3.1.5 on 2021-01-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0002_auto_20210118_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinary',
            name='county',
            field=models.CharField(max_length=30),
        ),
    ]
