# Generated by Django 3.1.5 on 2021-01-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0003_auto_20210118_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinary',
            name='id_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='veterinary',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
