# Generated by Django 3.1.5 on 2021-01-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0004_auto_20210120_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinary',
            name='email',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='veterinary',
            name='id_no',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='veterinary',
            name='phone_number',
            field=models.IntegerField(unique=True),
        ),
    ]
